name: Test and Deploy backend
on:
  push:
    branches:
      - master
jobs:
  testAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm i
      - name: Generate prisma client
        run: npx generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALLOWED_ORIGIN: ${{ ALLOWED_ORIGIN }}
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALLOWED_ORIGIN: ${{ ALLOWED_ORIGIN }}