name: build
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
    branches:
      - main
jobs:
  testAndDeploy:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm i
        working-directory: ./backend
      - name: Apply pending migrations to db
        run: npx prisma migrate deploy
        working-directory: ./backend
      - name: Generate prisma client
        run: npx prisma generate
        working-directory: ./backend
      - name: Test
        run: npm run test
        working-directory: ./backend
      - name: Deploy to AWS
        run: node ./node_modules/serverless/bin/serverless.js deploy --stage prod
        working-directory: ./backend