name: build
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
    branches:
      - main
jobs:
  testAndDeploy:
    env:
      DATABASE_URL: 'postgres://pwsobkvnqkhtom:cf359361c40657536b98a815aebbfe3b7bd3189737a77973bb3ecc5b049c3edf@ec2-54-145-139-208.compute-1.amazonaws.com:5432/d4u7vm8s630ih6'
      JWT_SECRET: 'secret'
      ALLOWED_ORIGIN: *
#       SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm i
        working-directory: ./backend
#       - name: Apply pending migrations to db
#         run: npx prisma migrate deploy
#         working-directory: ./backend
      - name: Generate prisma client
        run: npx prisma generate
        working-directory: ./backend
      - name: Test
        run: npm run test
        working-directory: ./backend
      - name: Deploy to AWS
        run: node ./node_modules/serverless/bin/serverless.js deploy --stage prod
        working-directory: ./backend
