name: build
on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
jobs:
  testAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm i
        working-directory: ./backend
      - name: Generate prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
        working-directory: ./backend
      - name: test
        run: npm run test
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
      - name: deploy
        run: node ./node_modules/serverless/bin/serverless.js deploy --stage prod
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}